### ISSUE TITLE
Deprecated version on php is supported

### ISSUE THREAD

**Issue by vv12131415** [cloudipsp/php-sdk-v2#1]
I saw this
https://github.com/cloudipsp/php-sdk-v2/blob/ae61e47efd402fe104785bc89473150db8fa248d/composer.json#L14

I think it's not necessary to support version that was dropped in 2015

Please rise supported version to 7.2 please

**Comment by has-well** [comment]
Hello, it's a minimum required PHP version, so sdk supported all php versions after 5.4, but if it confused you i will update requriments.
