### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by dnmisha** [cloudipsp/php-sdk-v2#2]
Exception in cloudipsp/php-sdk-v2/lib/Helper/ValidationHelper.php:112
$checksum += (int)($number{$i - 1});
Curly brace syntax for accessing array elements and string offsets has been deprecated in PHP 7.4
fix or change require php pversion pls

**Comment by has-well** [comment]
Hello, "PHP 7.4 will deprecate the curly brace syntax for accessing array elements and string offsets and it is expected that support will be completely removed in PHP 8.0.", so it works at v7.4.0RC4, now just depercated message not Exception
The issue will be fixed in next versions
