### ISSUE TITLE
Generate a payment url knowing order_id

### ISSUE THREAD

**Issue by Artem2710** [cloudipsp/php-sdk-v2#7]
Good day! Can you tell me how I can generate a payment url knowing order_id?

**Comment by has-well** [comment]
Good day, https://cloudipsp.github.io/php-docs/#checkout, just add your order_id to request params

**Comment by Artem2710** [comment]
If I pass order_id, then I have an error ```Duplicate order `1396424_e78824fe540d29c1ade7cba0c1667100` for merchant `1396424`.
    Request is incorrect.``` How can i generate url with the same order_id?

**Comment by has-well** [comment]
Order id is a unique value for merchant, you can't pass similar id with different order parameter

**Comment by Artem2710** [comment]
Ok, how can I generate url for an existing order?

**Comment by has-well** [comment]
At now, we don't have an api that returns existing order payment url, you can store it (url or payment token) on your side (session, db, memory db like redis) by order lifetime.

**Comment by Artem2710** [comment]
OK, thanks for answer)
