### ISSUE TITLE
about subscription end time and server call back 

### ISSUE THREAD

**Issue by thunderhurt** [cloudipsp/php-sdk-v2#9]
hi i am php developer and
i have some issues and quistions please : 
1- how to set end time for subscription , i want to share code : 

              
              \Cloudipsp\Configuration::setMerchantId(1396424);
              \Cloudipsp\Configuration::setSecretKey('test');
                \Cloudipsp\Configuration::setApiVersion('2.0');
                        $data = [
                                'currency' => 'USD',
	                        'amount' => 1500,
                                'response_url' => 'http://site.com/responseurl',
                                'server_callback_url' => 'http://site.com/callbackurl',
                               'subscription_callback_url' => 'http://site.com/subscription_callback_url',
              
              
              
              
                                                 'recurring_data' => [
                                                        'start_time' => '2021-11-02',
                                                        'amount' => 1000,
                                                        'every' => 30,
                                                        'period' => 'day',
			                                            'end_time' => '2021-12-02',
                                                        'state' => 'y',
                                                        'readonly' => 'y'
                                                       
                                                    ]
                              
                        ];
              \Cloudipsp\Subscription::url($data)->toCheckout();
		              
		              
		              
	              }

**### isuues :** 

**A****fondy page does not show start time or end time 
**B**** in my code as you can see , fondy will charge my client 15 usd then 10 usd every month , every 02 day from each month fondy will take 10 usd , is that right how i understand ? 
there is no end time in php but i found that there is end time in this link 

https://docs.fondy.eu/en/docs/page/14/

and the most important question is : 
in my code is right how i write the code ? i mean in php documentation there is nothing about server call back for subscriptions , and how i will be able to make sure that subscription paid 

**C**** if subscription not paid , how to receive the call back , ok i can print_r data but please give us as much as you can details so we understand better 
**D**** let us say that user after 2 month , there was no money in his card , fondy will cancel subscription or try again in next day and how many times fondy will try to take money from card 

really sorry for taking your time and thank you so much for this great service .

**Comment by thunderhurt** [comment]
i can see from old issues that you answer in the same day , i hope that you are good and healthy 🌹🌹

**Comment by thunderhurt** [comment]
hello sir please just let me know if you seen this , because i think you did not seen this 🌹

**Comment by has-well** [comment]
Hello, sorry but it's not sdk issues, try contact support@fondy.eu for answers about callback params and subscription logic. Have a nice day!
